[package]
name = "axiom"
version = "0.1.0"
description = "AXIOM — Learn architecture, structures, materials"
authors = ["AXIOM"]
edition = "2021"
repository = ""
rust-version = "1.77.2"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.0.0", features = [] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
